config/routes.rb
Rails.application.routes.draw do
  resources :user_notes
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/user_note.rb
class UserNote < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_notes_controller.rb
class UserNotesController < ApplicationController
  before_action :set_user_note, only: %i[ show edit update destroy ]

  # GET /user_notes or /user_notes.json
  def index
    @user_notes = UserNote.all
  end

  # GET /user_notes/1 or /user_notes/1.json
  def show
  end

  # GET /user_notes/new
  def new
    @user_note = UserNote.new
  end

  # GET /user_notes/1/edit
  def edit
  end

  # POST /user_notes or /user_notes.json
  def create
    @user_note = UserNote.new(user_note_params)

    respond_to do |format|
      if @user_note.save
        format.html { redirect_to user_note_url(@user_note), notice: "User note was successfully created." }
        format.json { render :show, status: :created, location: @user_note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_notes/1 or /user_notes/1.json
  def update
    respond_to do |format|
      if @user_note.update(user_note_params)
        format.html { redirect_to user_note_url(@user_note), notice: "User note was successfully updated." }
        format.json { render :show, status: :ok, location: @user_note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_notes/1 or /user_notes/1.json
  def destroy
    @user_note.destroy!

    respond_to do |format|
      format.html { redirect_to user_notes_url, notice: "User note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_note
      @user_note = UserNote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_note_params
      params.require(:user_note).permit(:user_id, :note)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_notes_helper.rb
module UserNotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnjoyRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_notes/_form.html.erb
<%= form_with(model: user_note) do |form| %>
  <% if user_note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_note.errors.count, "error") %> prohibited this user_note from being saved:</h2>

      <ul>
        <% user_note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :note, style: "display: block" %>
    <%= form.text_area :note %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_notes/_user_note.html.erb
<div id="<%= dom_id user_note %>">
  <p>
    <strong>User:</strong>
    <%= user_note.user_id %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= user_note.note %>
  </p>

</div>

app/views/user_notes/edit.html.erb
<h1>Editing user note</h1>

<%= render "form", user_note: @user_note %>

<br>

<div>
  <%= link_to "Show this user note", @user_note %> |
  <%= link_to "Back to user notes", user_notes_path %>
</div>

app/views/user_notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User notes</h1>

<div id="user_notes">
  <% @user_notes.each do |user_note| %>
    <%= render user_note %>
    <p>
      <%= link_to "Show this user note", user_note %>
    </p>
  <% end %>
</div>

<%= link_to "New user note", new_user_note_path %>

app/views/user_notes/new.html.erb
<h1>New user note</h1>

<%= render "form", user_note: @user_note %>

<br>

<div>
  <%= link_to "Back to user notes", user_notes_path %>
</div>

app/views/user_notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_note %>

<div>
  <%= link_to "Edit this user note", edit_user_note_path(@user_note) %> |
  <%= link_to "Back to user notes", user_notes_path %>

  <%= button_to "Destroy this user note", @user_note, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>